CREATE TABLE tb_vendedor(
cod_vendedor INT AUTO_INCREMENT PRIMARY KEY,
nm_nome VARCHAR (100) NOT NULL, 
nr_celular INT (12) NOT NULL UNIQUE,
ds_email VARCHAR(100) NOT NULL UNIQUE,
data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);